### ISSUE TITLE
Where did I go wrong?

### ISSUE THREAD

**Issue by xhackermanx** [ValeriyMaslenikov/tg-notify-deleted-messages#10]
Попробовал и под win и под Ubuntu 20.04.5

# docker-compose create --force-recreate --build app && docker-compose run app python ./src/monitor.py auth
WARNING: The create command is deprecated. Use the up command with the --no-start flag instead.
Building app
Step 1/6 : FROM python:3-alpine
 ---> 426bd32e71b2
Step 2/6 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 5771f4159a1c
Step 3/6 : COPY requirements.txt ./
 ---> Using cache
 ---> bf553143d65a
Step 4/6 : RUN pip install --no-cache-dir -r requirements.txt
 ---> Using cache
 ---> 78dac69834f7
Step 5/6 : COPY . .
 ---> 44be1b9dd737
Step 6/6 : CMD [ "python", "./monitor.py" ]
 ---> Running in 7324020cc08e
Removing intermediate container 7324020cc08e
 ---> 1b9d15bab2b7
Successfully built 1b9d15bab2b7
Successfully tagged tg-notify-deleted-messages-100_app:latest
Creating tg-notify-deleted-messages-100_app_1 ... done
Traceback (most recent call last):
  File "/usr/src/app/./src/monitor.py", line 49, in <module>
    with TelegramClient('db/user', os.getenv("TELEGRAM_API_ID"), os.getenv("TELEGRAM_API_HASH")) as client:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telethon/client/telegrambaseclient.py", line 337, in __init__
    self._sender = MTProtoSender(
                   ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/telethon/network/mtprotosender.py", line 58, in __init__
    self._connect_lock = asyncio.Lock(loop=loop)
                         ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Lock.__init__() got an unexpected keyword argument 'loop'

**Comment by camalouu** [comment]
I have the same problem.

**Comment by JonasSchatz** [comment]
The `loop` parameter in many `asyncio` functions has been deprecated and was scheduled to be removed in Python 3.10. The `dockerfile` however uses the latest version of Python 3. You might want to edit the first line to `FROM python:3.9.16-alpine3.17` or use the fork @henry701 created at https://github.com/henry701/tg-notify-deleted-messages
