### ISSUE TITLE
При удалении сообщения не удается найти объект

### ISSUE THREAD

**Issue by Q0** [ValeriyMaslenikov/tg-notify-deleted-messages#2]
**Мои действия:**

1. Аккаунт №2 отправляет сообщение на аккаунт №1
2. Аккаунт №2 удаляет свое сообщение
3. Появляется ошибка в консоли, удаленное сообщение не пересылается на аккаунт №1

Строка в логе сдвинута на +1, т.к я модифицировал код и добавил `import socks` и прокси в `TelegramClient`.

Есть идеи в чем может быть проблема и как исправить?

```
ERROR:telethon.update_state:Unhandled exception on worker 0
Traceback (most recent call last):
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\update_state.py", line 106, in _worker_loop
    self.handler(update)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\telegram_client.py", line 2347, in _on_handler
    callback(event)
  File "monitor.py", line 106, in handler
    user_request = client(GetFullUserRequest(message.from_id))
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\telegram_bare_client.py", line 471, in __call__
    r.resolve(self, utils)
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\tl\functions\users.py", line 28, in resolve
    self.id = utils.get_input_user(client.get_input_entity(self.id))
  File "C:\Users\Paul\AppData\Local\Programs\Python\Python36-32\lib\site-packages\telethon\telegram_client.py", line 2657, in get_input_entity
    .format(peer)
ValueError: Could not find the input entity for "506785601". Please read https://telethon.readthedocs.io/en/latest/extra/basic/entities.html to find out more details.
```

**Comment by ValeriyMaslenikov** [comment]
@Q0 действия судя по всему совершаются правильные.
Для того чтобы убедится что проблема не в окружении, а в самой библиотеке, давайте попробуем собрать приложение рекомендуемым в документации способом, тогда мы исключим бока библиотеки Telethon связанные с Windows.
